services:
  nginx-proxy:
    build:
      context: .
      dockerfile: "./nginx/Dockerfile-nginx"
    ports:
      - "80:80"
    depends_on:
      - dash-app
    networks:
      - inside
      - outside
  dash-app:
    build: 
      context: .
      dockerfile: "./app/Dockerfile-dev-dash"
    ports:
      - "8050:8050"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - inside
networks:
  inside:
    internal: true
  outside:
