# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "poetry==1.8.4"
        poetry install --with dev,config
    - name: Lint with ruff
      uses: astral-sh/ruff-action@v2
    - name: move up one directory
      run: |
        cd ..
    - name: build and run docker container
      run: |
        docker compose -f docker-compose-dev.yaml up
    - name: run tests
      run: |
        docker exec hubmap-pancreas-data-explorer-display-app-1 pytest
        