# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Lint with ruff
      uses: astral-sh/ruff-action@v2
    - name: print contents of current directory
      run: |
        ls
    - name: create docker volume
      run: |
        docker volume create config-data
    - name: copy starter data into docker volume
      run : |
        docker run --name temp -v config-data:/data busybox
        docker cp -a ./start/ temp:/data/
        docker stop temp
    - name: build and run docker container
      run: |
        docker compose -f docker-compose-dev.yaml up
    - name: run tests
      run: |
        docker exec hubmap-pancreas-data-explorer-display-app-1 pytest
        